SELECT * FROM 
DROP VIEW vw_students

CREATE TABLE sales(saledate DATETIME PRIMARY KEY,
qty INT)
INSERT INTO sales VALUES('2006-01-01',100)
INSERT INTO sales VALUES('2006-02-01',200)
INSERT INTO sales VALUES('2006-03-01',100)
INSERT INTO sales VALUES('2006-04-01',100)

DROP VIEW vw_sgn

CREATE VIEW vw_sgn AS
SELECT CAST(s1.saledate AS VARCHAR(50))+
'..'+CAST(s2.saledate AS VARCHAR(50)) 'Date',
SIGN((s1.qty-s2.qty))'sgn'
FROM sales s1 INNER JOIN sales s2
ON s1.saledate=DATEADD(mm,-1,s2.saledate)

SELECT * FROM vw_sgn

CREATE VIEW Trend AS
SELECT 'Tren Time : ' + date 'date',
CASE sgn WHEN -1 THEN 'Down'
WHEN 1 THEN 'Up' 
WHEN 0 THEN 'Same'
END 'Trend'
FROM vw_sgn

SELECT * FROM trend

CREATE TABLE sampletbl(id INT IDENTITY PRIMARY KEY,
title VARCHAR(50))
GO
CREATE VIEW vw_s AS
SELECT * FROM sampletbl
GO
SELECT * FROM vw_s
GO
ALTER TABLE sampletbl ADD d DATETIME DEFAULT GETDATE()
GO
SELECT * FROM vw_s
GO
SP_REFRESHVIEW 'vw_s'
GO
SELECT * FROM vw_s

SELECT 'EXEC SP_REFRESHVIEW '+QUOTENAME(QUOTENAME(TABLE_SCHEMA)+
'.'+QUOTENAME(TABLE_NAME),'''')
FROM INFORMATION_SCHEMA.VIEWS

CREATE TABLE nPhones(Row INT IDENTITY PRIMARY KEY,
Family VARCHAR(50),
Name VARCHAR(50),
Phone VARCHAR(50),
Username VARCHAR(50) DEFAULT SUSER_SNAME())

CREATE VIEW vw_np AS
SELECT * FROM nphones 
WHERE username=SUSER_SNAME()

GRANT INSERT,SELECT ON vw_np TO PUBLIC