CREATE TABLE tbl10(
ID UNIQUEIDENTIFIER PRIMARY KEY,
Name VARCHAR(50))
GO
CREATE PROC INS @n VARCHAR(50) AS
INSERT INTO tbl10 VALUES(NEWID(),@n)
GO
EXEC INS 'sample00'
GO
EXEC INS 'sample01' 
GO
EXEC INS 'sample02'
GO
EXEC INS 'sample03' 
GO
SELECT * FROM tbl10
GO
INSERT INTO tbl10 (id,name)
VALUES(NEWID(),'sample05')
GO
SELECT * FROM tbl10
GO 
UPDATE tbl10
SET name='sample05'
WHERE name='sample55'
GO
SELECT * FROM tbl10
GO