BEGIN TRAN 
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
GO
SELECT * FROM tbl10
WHERE name>'c'
CREATE NONCLUSTERED INDEX ix_sample
ON tbl10(name)
CREATE TABLE sCOURSES(CID INT PRIMARY KEY,Title VARCHAR(50))
CREATE TABLE LESSONS(CID INT,LID INT,Title VARCHAr(50),PRIMARY KEY(CID,LID))

CREATE VIEW vw AS
SELECT c.title 'Course Title',l.title 'Lesson Title'
FROM sCourses c INNER JOIN lessons l
ON c.cid=l.cid

SELECT * FROM vw