CREATE TRIGGER tg_Create ON DATABASE FOR CREATE_TABLE AS
	PRINT CAST(eventdata() AS NVARCHAR(MAX))
GO
CREATE TABLE tbl01(id INT)

PRINT(OBJECTPROPERTY(OBJECT_ID('Marks'),'TableHasPrimayKey'))

IF OBJECTPROPERTY(OBJECT_ID('Marks'),'TableHasPrimayKey')=0
	PRINT '0'
ELSE
	PRINT '<>0'

CREATE TRIGGER tg_Alter ON DATABASE FOR ALTER_TABLE AS
	DECLARE @e XML
	DECLARE @n NVARCHAR(MAX)
	SELECT @e=EVENTDATA()
	SELECT @n=CAST(@e.query('data(//objectname)') AS NVARCHAR(MAX))
	IF @n='tbl01'
			RAISERROR('No Change Is Supported !',16,1)
			ROLLBACK TRAN

	ALTER TABLE tbl01 ADD Title VARCHAR(50)

CREATE TRIGGER tg_Create ON DATABASE FOR CREATE_TABLE AS
	DECLARE @e XML
	DECLARE @n NVARCHAR(50)
	SET @e=EVENTDATA()
	SET @n=CAST(@e.query('data(//objectname)') AS NVARCHAR(50))
	IF OBJECTPROPERTY(OBJECT_ID(@n),'TableHasPrimaryKey')=0
		RAISERROR('msg',16,1)
		ROLLBACK TRAN